version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mailmon
      POSTGRES_PASSWORD: mailmonpassword
      POSTGRES_DB: mailmondb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailmon -d mailmondb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://mailmon:mailmonpassword@db:5432/mailmondb
      JWT_SECRET: change_me_secret
      JWT_ALG: HS256
      RATE_LIMIT_PER_MINUTE: "120"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:
